### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by mastepperhs** [LayerZero-Labs/LayerZero-v2#8]
<img width="1146" alt="image" src="https://github.com/LayerZero-Labs/LayerZero-v2/assets/153589435/2627160d-39de-4e59-b472-6c0c8df25fe5">

**Comment by Zodomo** [comment]
You need to provide constructor arguments before deploying

**Comment by aleksandr1101** [comment]
The issue is occured on the compiling stage

**Comment by Kuzirashi** [comment]
The problem is that when using Remix Ownable constructor needs to be manually called, potentially because Remix pulls mismatched version of OpenZeppelin.

Error:
![image](https://github.com/LayerZero-Labs/LayerZero-v2/assets/4950658/20d34da4-f44f-4331-888c-55f03cee1728)

Fixed error:
![image](https://github.com/LayerZero-Labs/LayerZero-v2/assets/4950658/3190f7ea-d691-4fd2-b5ba-835470094f2d)
